# Configuration for ArtFlow model
model:
  model_type: "artflow"
  input_channels: 3
  output_channels: 3
  flow_blocks: 4
  use_bijective: true

training:
  batch_size: 4
  num_epochs: 50
  learning_rate: 0.0002
  beta1: 0.9
  beta2: 0.999
  scheduler_type: "cosine"
  min_lr: 0.00001
  content_weight: 1.0
  style_weight: 5.0
  flow_weight: 0.1
  save_interval: 500
  validation_interval: 250

data:
  content_path: "data/coco"
  style_path: "data/wikiart"
  image_size: 256
  crop_size: 256
  use_augmentation: true
  num_workers: 4

logging:
  use_wandb: true
  project_name: "style-transfer"
  run_name: "artflow-experiment"
  log_interval: 100
  save_dir: "checkpoints/artflow"
  output_dir: "outputs/artflow" 