# Configuration for CNNMRF model
model:
  model_type: "cnnmrf"
  device: "cuda"
  patch_sizes: [3, 3, 3, 3]
  content_layer: 2

training:
  batch_size: 1
  num_steps: 500
  learning_rate: 1.0
  content_weight: 1.0
  mrf_weights: [1.0, 1.0, 1.0, 1.0]
  tv_weight: 1e-6
  save_interval: 50
  validation_interval: 50

data:
  content_path: "data/coco"
  style_path: "data/wikiart"
  image_size: 256
  crop_size: 256
  use_augmentation: false
  num_workers: 2

logging:
  use_wandb: true
  project_name: "style-transfer"
  run_name: "cnnmrf-experiment"
  log_interval: 50
  save_dir: "checkpoints/cnnmrf"
  output_dir: "outputs/cnnmrf" 