# Configuration for CycleGAN model
model:
  model_type: "cyclegan"
  input_channels: 3
  output_channels: 3
  base_filters: 64
  n_residual_blocks: 9
  use_dropout: true
  norm_type: "instance"
  activation: "relu"
  init_type: "normal"

training:
  batch_size: 32
  num_epochs: 200
  learning_rate: 0.0001
  beta1: 0.5
  beta2: 0.999
  scheduler_type: "linear"
  n_epochs_decay: 100
  lambda_A: 10.0
  lambda_B: 10.0
  lambda_identity: 0.1
  pool_size: 50
  save_interval: 500
  validation_interval: 200
  early_stopping: true
  patience: 10
   

data:
  dataset_path: "data/"
  content_path: "data/coco"
  style_path: "data/style"
  image_size: 256
  crop_size: 256
  train_content_size: 20000
  train_style_size: 1500
  val_content_size: 2000
  val_style_size: 150
  use_augmentation: true
  num_workers: 16

logging:
  use_wandb: true
  project_name: "style-transfer"
  run_name: "cyclegan-baseline"
  log_interval: 50
  save_dir: "checkpoints/cyclegan"
  output_dir: "outputs/cyclegan"
  save_best: true
  metric_interval: 100