# Configuration for Deep Image Analogy model
model:
  model_type: "deep_image_analogy"
  device: "cuda"
  patch_size: 3
  iterations: 5
  alpha: 0.5
  level_weights: [1.0, 0.8, 0.6, 0.4, 0.2]

training:
  batch_size: 1
  num_epochs: 50
  save_interval: 500
  validation_interval: 250

data:
  source_path: "data/source"
  target_path: "data/target"
  image_size: 256
  crop_size: 256
  use_augmentation: false
  num_workers: 2

logging:
  use_wandb: true
  project_name: "image-analogy"
  run_name: "deep-image-analogy-experiment"
  log_interval: 100
  save_dir: "checkpoints/deep_image_analogy"
  output_dir: "outputs/deep_image_analogy" 