# Configuration for model evaluation
evaluation:
  metrics:
    content_loss: true
    style_loss: true
    lpips: true
    fid: true
    psnr: true
    ssim: true
  
  batch_size: 16
  num_workers: 4
  device: "cuda"
  
  # Content preservation thresholds
  content_loss_threshold: 2.0
  lpips_threshold: 0.5
  psnr_threshold: 20.0
  ssim_threshold: 0.7
  
  # Style transfer thresholds
  style_loss_threshold: 1.0
  style_consistency_threshold: 0.8
  
  # FID score threshold
  fid_threshold: 100.0

visualization:
  save_images: true
  create_grid: true
  max_samples: 64
  grid_size: [8, 8]
  
  plots:
    metrics_history: true
    style_consistency: true
    content_preservation: true
    comparison_heatmap: true

output:
  save_metrics: true
  save_visualizations: true
  generate_report: true
  output_dir: "evaluation_results" 