# Configuration for experimental setup
experiment:
  name: "style_transfer_comparison"
  description: "Comparison of different style transfer models"
  seed: 42
  
  models:
    - name: "adain"
      config: "configs/adain_config.yaml"
      checkpoint: "checkpoints/adain/best.pth"
    
    - name: "cyclegan"
      config: "configs/cyclegan_config.yaml"
      checkpoint: "checkpoints/cyclegan/best.pth"
    
    - name: "johnson"
      config: "configs/johnson_config.yaml"
      checkpoint: "checkpoints/johnson/best.pth"

  datasets:
    content:
      - name: "coco"
        path: "data/coco/test"
      - name: "places365"
        path: "data/places365/test"
    
    style:
      - name: "wikiart"
        path: "data/wikiart/test"
      - name: "artists"
        path: "data/artist_styles"

  metrics:
    - content_loss
    - style_loss
    - lpips
    - fid
    - psnr
    - ssim

  analysis:
    style_consistency: true
    content_preservation: true
    cross_dataset: true
    statistical_tests: true

  visualization:
    generate_plots: true
    save_samples: true
    create_report: true

  output:
    base_dir: "experiment_results"
    save_metrics: true
    save_models: true
    save_visualizations: true 