# Configuration for FastPhotoStyle model
model:
  model_type: "fastphotostyle"
  input_channels: 3
  output_channels: 3
  photorealism_weight: 1.0

training:
  batch_size: 4
  num_epochs: 50
  learning_rate: 0.0002
  beta1: 0.9
  beta2: 0.999
  content_weight: 1.0
  style_weight: 5.0
  photorealism_weight: 10.0
  save_interval: 500
  validation_interval: 250

data:
  content_path: "data/photos"
  style_path: "data/styles"
  image_size: 256
  crop_size: 256
  use_augmentation: true
  num_workers: 4
  use_fiftyone: true

logging:
  use_wandb: true
  project_name: "style-transfer"
  run_name: "fastphotostyle-experiment"
  log_interval: 100
  save_dir: "checkpoints/fastphotostyle"
  output_dir: "outputs/fastphotostyle" 