# Configuration for GatysModel
model:
  model_type: "gatys"
  content_layers: ['conv4_2']
  style_layers: ['conv1_1', 'conv2_1', 'conv3_1', 'conv4_1', 'conv5_1']
  num_steps: 300
  style_weight: 1e6
  content_weight: 1.0

training:
  batch_size: 1
  learning_rate: 1.0
  save_interval: 50
  validation_interval: 50

data:
  content_path: "data/photos"
  style_path: "data/styles"
  image_size: 256
  crop_size: 256
  use_augmentation: false
  num_workers: 2
  use_fiftyone: true
  dataset_name: "style_transfer_dataset" 

logging:
  use_wandb: false
  project_name: "style-transfer"
  run_name: "gatysmodel-experiment"
  log_interval: 50
  save_dir: "checkpoints/gatysmodel"
  output_dir: "outputs/gatysmodel" 