# Configuration for Johnson model
model:
  model_type: "johnson"
  input_channels: 3
  output_channels: 3
  base_filters: 64
  n_residuals: 5
  use_dropout: true
  norm_type: "instance"
  style_model: "vgg19"
  content_layers: ["relu4_2"]
  style_layers: ["relu1_2", "relu2_2", "relu3_3", "relu4_3"]

training:
  batch_size: 4
  num_epochs: 100
  learning_rate: 0.001
  beta1: 0.9
  beta2: 0.999
  scheduler_type: "step"
  step_size: 30
  gamma: 0.1
  content_weight: 1.0
  style_weight: 5.0
  tv_weight: 1e-6
  save_interval: 500
  validation_interval: 250

data:
  content_path: "data/coco"
  style_path: "data/styles/starry_night.jpg"
  image_size: 256
  crop_size: 256
  use_augmentation: true
  num_workers: 4

logging:
  use_wandb: true
  project_name: "style-transfer"
  run_name: "johnson-starry-night"
  log_interval: 100
  save_dir: "checkpoints/johnson"
  output_dir: "outputs/johnson" 