# Configuration for Johnson model
model:
  model_type: "johnson"
  input_channels: 3
  output_channels: 3
  base_filters: 32
  n_residuals: 5
  use_dropout: true
  norm_type: "instance"
  style_model: "vgg19"
  content_layers: ["relu3_3"]  # Changed from relu4_2
  style_layers: ["relu1_2", "relu2_2", "relu3_3", "relu4_3"]  # Modified layer selection

training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.00005
  beta1: 0.5
  beta2: 0.999
  scheduler_type: "step"
  step_size: 20
  gamma: 0.5
  content_weight: 0.1
  style_weight: 25.0
  tv_weight: 0.01
  save_interval: 500
  validation_interval: 5000
  min_lr: 0.00001
  gradient_clip: 5.0

data:
  dataset_path: "data/"
  content_path: "data/coco"
  style_path: "data/style"
  image_size: 256
  crop_size: 256
  train_content_size: 20000
  train_style_size: 1500
  val_content_size: 2000
  val_style_size: 150
  use_augmentation: true
  num_workers: 16

logging:
  use_wandb: true
  project_name: "style-transfer"
  run_name: "johnson-baseline"
  log_interval: 100
  save_dir: "checkpoints/johnson"
  output_dir: "outputs/johnson"
  visualization:
    sample_interval: 500  # Save samples every N batches
    num_samples: 4        # Number of samples to save
    save_style_targets: true  # Save style target images
  save_best: true
  metric_interval: 100
