# Configuration for MSGNet model
model:
  model_type: "msgnet"
  input_nc: 3
  output_nc: 3
  ngf: 64
  n_blocks: 6
  n_styles: 32

training:
  batch_size: 4
  num_epochs: 50
  learning_rate: 0.0002
  beta1: 0.9
  beta2: 0.999
  scheduler_type: "linear"
  n_epochs_decay: 25
  content_weight: 1.0
  style_weight: 5.0
  save_interval: 500
  validation_interval: 250

data:
  content_path: "data/coco"
  style_path: "data/wikiart"
  image_size: 256
  crop_size: 256
  use_augmentation: true
  num_workers: 4

logging:
  use_wandb: true
  project_name: "style-transfer"
  run_name: "msgnet-experiment"
  log_interval: 100
  save_dir: "checkpoints/msgnet"
  output_dir: "outputs/msgnet" 