# Configuration for Neural Doodle model
model:
  model_type: "neural_doodle"
  device: "cuda"
  patch_size: 3
  stride: 1

training:
  batch_size: 1
  num_steps: 500
  learning_rate: 1.0
  content_weight: 1.0
  style_weight: 5.0
  save_interval: 100
  validation_interval: 100

data:
  content_path: "data/content"
  style_path: "data/style"
  doodle_path: "data/doodle"
  style_regions_path: "data/style_regions"
  image_size: 256
  crop_size: 256
  use_augmentation: false
  num_workers: 2

logging:
  use_wandb: true
  project_name: "semantic-style-transfer"
  run_name: "neural-doodle-experiment"
  log_interval: 100
  save_dir: "checkpoints/neural_doodle"
  output_dir: "outputs/neural_doodle" 