# Configuration for ReStyle model
model:
  model_type: "restyle"
  input_channels: 3
  output_channels: 3
  num_iterations: 5
  use_attention: true
  feature_layers: ["relu1_1", "relu2_1", "relu3_1"]
  use_dropout: true

training:
  batch_size: 4
  num_epochs: 40
  learning_rate: 0.0001
  beta1: 0.9
  beta2: 0.999
  scheduler_type: "step"
  step_size: 10
  gamma: 0.5
  content_weight: 1.0
  style_weight: 10.0
  save_interval: 200
  validation_interval: 100

data:
  content_path: "data/coco"
  style_path: "data/wikiart"
  image_size: 256
  crop_size: 256
  use_augmentation: true
  num_workers: 4
  use_fiftyone: true

logging:
  use_wandb: true
  project_name: "style-transfer"
  run_name: "restyle-experiment"
  log_interval: 100
  save_dir: "checkpoints/restyle"
  output_dir: "outputs/restyle" 