# Configuration for STROTSS model
model:
  model_type: "strotss"
  input_channels: 3
  output_channels: 3
  content_weight: 1.0
  style_weight: 1.0
  reg_weight: 1e-4
  use_dropout: false

training:
  batch_size: 2
  num_epochs: 30
  learning_rate: 0.0002
  beta1: 0.5
  beta2: 0.999
  scheduler_type: "linear"
  n_epochs_decay: 15
  save_interval: 100
  validation_interval: 50

data:
  content_path: "data/coco"
  style_path: "data/wikiart"
  image_size: 256
  crop_size: 256
  use_augmentation: false
  num_workers: 2
  use_fiftyone: true

logging:
  use_wandb: true
  project_name: "style-transfer"
  run_name: "strotss-experiment"
  log_interval: 50
  save_dir: "checkpoints/strotss"
  output_dir: "outputs/strotss" 