# Configuration for StyleGAN2-ADA model
model:
  model_type: "stylegan2ada"
  z_dim: 512
  w_dim: 512
  c_dim: 0
  img_resolution: 1024
  img_channels: 3
  g_lr: 0.002
  d_lr: 0.002
  mixing_prob: 0.9

training:
  batch_size: 16
  num_epochs: 100
  save_interval: 500
  validation_interval: 250

data:
  train_path: "data/train"
  val_path: "data/val"
  image_size: 1024
  use_augmentation: true
  num_workers: 4
  use_fiftyone: true

logging:
  use_wandb: true
  project_name: "stylegan2ada-training"
  run_name: "stylegan2ada-experiment"
  log_interval: 100
  save_dir: "checkpoints/stylegan2ada"
  output_dir: "outputs/stylegan2ada" 