# Configuration for StyleFormer model
model:
  model_type: "styleformer"
  input_channels: 3
  output_channels: 3
  img_size: 256
  patch_size: 16
  embed_dim: 512
  depth: 6
  num_heads: 8
  mlp_ratio: 4.0
  qkv_bias: true
  drop_rate: 0.1
  attn_drop_rate: 0.1

training:
  batch_size: 4
  num_epochs: 50
  learning_rate: 0.0003
  beta1: 0.9
  beta2: 0.999
  scheduler_type: "cosine"
  min_lr: 0.00001
  content_weight: 1.0
  style_weight: 5.0
  save_interval: 500
  validation_interval: 250

data:
  content_path: "data/coco"
  style_path: "data/wikiart"
  image_size: 256
  crop_size: 256
  use_augmentation: true
  num_workers: 4

logging:
  use_wandb: true
  project_name: "style-transfer"
  run_name: "styleformer-experiment"
  log_interval: 100
  save_dir: "checkpoints/styleformer"
  output_dir: "outputs/styleformer" 