# Test configuration for quick model validation
model:
  model_type: "adain"
  input_channels: 3
  output_channels: 3
  encoder_type: "vgg19"
  decoder_type: "basic"
  content_layers: ["relu4_1"]
  style_layers: ["relu1_1", "relu2_1", "relu3_1", "relu4_1"]
  use_dropout: true

training:
  batch_size: 4
  num_epochs: 1
  learning_rate: 0.0001
  beta1: 0.5
  beta2: 0.999
  scheduler_type: "cosine"
  min_lr: 0.00001
  content_weight: 1.0
  style_weight: 10.0
  save_interval: 50
  validation_interval: 25
  clip_grad_norm: true
  max_grad_norm: 5.0

data:
  dataset_path: "data/"
  content_path: "data/coco"
  style_path: "data/style"
  image_size: 256
  crop_size: 224
  train_content_size: 100
  train_style_size: 20
  val_content_size: 20
  val_style_size: 10
  use_augmentation: true
  num_workers: 4

logging:
  use_wandb: false  # Disabled wandb for testing
  project_name: "style-transfer"
  run_name: "test-run"
  log_interval: 10
  save_dir: "checkpoints/test"
  output_dir: "outputs/test" 